# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Onatrix-webApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: dotnet restore
        run: dotnet restore "./OnatrixWebApi.sln"  # Adjust the path as needed
        
      - name: Build with dotnet
        run: dotnet build "./OnatrixWebApi.sln" --configuration Release

      - name: Publish
        run: dotnet publish "./OnatrixWebApi/OnatrixWebApi.csproj" --configuration Release --output "B:\\CMS_ECutbildning\\OnatrixWebApi\\OnatrixWebApi\\bin\\Release\\net8.0\\publish"

      - name: List Output Directory
        run: ls "B:\\CMS_ECutbildning\\OnatrixWebApi\\OnatrixWebApi\\bin\\Release\\net8.0\\publish"  # Check published files

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "B:\\CMS_ECutbildning\\OnatrixWebApi\\OnatrixWebApi\\bin\\Release\\net8.0\\publish"  # Use the correct output path
          
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC39CEB06C6244409D3CE49CFB6B55F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_337B9AC8E4F84AABBADD3583B32F542C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CAF90D7FEC154DF78C0186F409CA8815 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Onatrix-webApi'
          slot-name: 'Production'
          package: .
          
